### PR TITLE
Add Flip option to conversation system

### PR DESCRIPTION
**Pull request by lealeelu**
Whatever direction the character is facing, flip them to the opposite direction. Doesn't work if they are facing forward.

### CODE REVIEW

**Comment by chrisgregan** [comment]
Hey - will I merge this PR as is or do you want to make changes for the left / right facing stuff?

**Comment by lealeelu** [comment]
Ok, I think it's ready to merge now.

**Comment by chrisgregan** [comment]
Looking good. Gonna step through it in the morning and then merge.

**Comment by chrisgregan** [comment]
Thanks Leah!

**Pull request merged**
