### PR TITLE
Improve Performace for Singleton

### PR DESCRIPTION
**Pull request by AndyHan1001**
Use "double checked locking" algorithm to implement singleton for "FungusManger" class, which can improve performace.

### CODE REVIEW

**Comment by stevehalliwell** [comment]
Hey AndyHan, thanks for putting in a PR. Did you have a use case for multithreaded access to the FungusManager?

**Comment by AndyHan1001** [comment]
> Hey AndyHan, thanks for putting in a PR. Did you have a use case for multithreaded access to the FungusManager?

Hi stevehalliwell, I am sorry, I do not have any use cases for that, but "double checked locking" algorithm is a proven method to handle multithreaded cases and guarantee the performance at the same time.

**Comment by stevehalliwell** [comment]
Thanks Andy, I was wondering if this was in response to a specific need or situation you found as my concern is this makes it look like Fungus is thread safe and/or thread aware, when it isn't. 

Related, much of Unity itself will throw errors back at you if you try to interact with it from anything other than Unity's MainThread. If we called FungusManager.Instance on another thread when it was null, new GameObject, DontDestroy, and AddComponent might just throw back errors from Unity.

**Comment by AndyHan1001** [comment]
> Thanks Andy, I was wondering if this was in response to a specific need or situation you found as my concern is this makes it look like Fungus is thread safe and/or thread aware, when it isn't.
> 
> Related, much of Unity itself will throw errors back at you if you try to interact with it from anything other than Unity's MainThread. If we called FungusManager.Instance on another thread when it was null, new GameObject, DontDestroy, and AddComponent might just throw back errors from Unity.

Right, but my pull request is just for performance improvement. No extra function is added. Your original code will always lock the thread if you access instance of FungusManager, which is time consuming. My pull request code only need to lock the thread once, which can improve performance significantly if the instance of FungusManager is accessed frequently.

**Comment by stevehalliwell** [comment]
Yep, I missed that line change in the diff preview. Merging in changes to FungusManager.cs now and trying to avoid all the meta changes.

Thanks.

**Pull request closed without merging**
