### PR TITLE
Bugfix: Additional GetSummary condition for StringData

### PR DESCRIPTION
**Pull request by funkyApe**
I´m very new to Git and also Github, please tell me
if something is wrong with the request

### CODE REVIEW

**Comment by chrisgregan** [comment]
Thanks for the pull request! Looks like some nice additions in here, it'll take me a while to go through them all and get them merged.

Just in future, it's easier on my end if each change is sent in as its own pull request rather than all together. Keep 'em coming :)

**Comment by funkyApe** [comment]
Hi, 
the first pull request was only the bugfix, all my other commits to the fork were automatically in
the pull request... how to avoid it?

**Comment by Pavelko007** [comment]
Read this article - https://2buntu.com/articles/1459/keeping-your-forked-repo-synced-with-the-upstream-source/
There is many useful information in it

**Comment by chrisgregan** [comment]
Cheers for the article. I'm still slowly getting my head around git myself! btw I think the thing you want to do is [cherry pick](https://www.kernel.org/pub/software/scm/git/docs/git-cherry-pick.html) the changes you want from your branch into a new branch and then make a pull request from the new branch.

Regarding the change, I fixed the root problem in the StringData and StringMultiData classes. Here's [the commit](https://github.com/snozbot/fungus/commit/f3d094c9085465065705c2a2a054af12da801a54).

Is there anything I need to merge from this PR now or can I close it?

**Comment by funkyApe** [comment]
Hi Chris,

if it´s possible please only ignore these two commits
Added onExecute action for single/specific callback method			a8e1467
Added new EventHandler for FlowChart based on ExecuteHandler			8be0cad

because I´m working on another structure for more usability in flowchart.

The Variable Support for EventHandlers, Getter/Setter for Variables and the additional ignoreTimeScale parameter for iTween commands would be nice for the next fungus version.

thanks

**Comment by chrisgregan** [comment]
Ok, I'll give it a go.

**Comment by chrisgregan** [comment]
Ok I've been trying to unpick these commits but it's complicated, and some of your changes will conflict with fixes I've made since. Would you mind if we try again with a separate PR for each feature?

Basically make a new branch o the latest master, apply the changes for one feature (e.g. iTween time scale) and send that in as its own PR. I'm very tight for time currently so this would make it waaaay easier for me to integrate the changes :)

**Pull request closed without merging**
