### PR TITLE
Made sure my save system works with the latest Fungus

### PR DESCRIPTION
**Pull request by CG-Tespy**

### CODE REVIEW

**Comment by stevehalliwell** [comment]
Hey CGT, thanks for the PR. I see you have split your additions out into their own folder. 

Did you intend for this to become part of core fungus? Or did you want it bundled with fungus but as an add on?

**Comment by CG-Tespy** [comment]
I intend for the save system to become part of core Fungus, yes. And if the powers that be would like to make it so, I suggest renaming the folder; it'd no longer be just my save system by that point xD

**Comment by stevehalliwell** [comment]
Cool. Is that work something you are looking at doing or are you wanting to hand this off?

**Comment by CG-Tespy** [comment]
Yes, I'd like to hand this off. Of course, if anyone finds any significant bugs in it, I'd like to be alerted so I can help fix said bugs.

**Comment by stevehalliwell** [comment]
OK, I'll pull this into a feature branch and make a new PR from there to do the changes and further testing on.

How would you like to be alerted? and thanks for the contribution.

**Comment by CG-Tespy** [comment]
Understood, thanks. And I'd like to be alerted through email

**Comment by stevehalliwell** [comment]
Consolidation of this and further improvements to save system ongoing here #795

**Pull request closed without merging**
