### PR TITLE
Command by name

### PR DESCRIPTION
**Pull request by stevehalliwell**
type command name

Added a text input box to the bottom of the Block Editor that allows user to type partial name of command and get a filtered list back that they can use up down arrows to navigate and enter to confirm.

Motivated by watching my students know they want an If or a Call but not having the muscle memory of where in the Generic Menu that is.

### CODE REVIEW

**Comment by MorningFunGame** [comment]
It is really cool, I love it !

**Comment by chrisgregan** [comment]
Very nice! Good use for that space.

Just going to do a bit more testing on it then I'll merge.

**Comment by chrisgregan** [comment]
This is a really cool feature, well done!

I spotted a few lines of commented out code (e.g BlockEditor.cs line 29). If those lines aren't needed anymore it would be better if they were deleted. Would you mind deleting them and then I'll merge in?

**Comment by stevehalliwell** [comment]
Sure thing, I'll look at it tonight after work or tomorrow.

**Comment by chrisgregan** [comment]
Awesome, thanks!

**Pull request merged**
