### PR TITLE
Refactored parts of the SBNS and extended it for a feature request

### PR DESCRIPTION
**Pull request by CG-Tespy**
### Description
New feature and (to help implement it) code refactors.

### What is the current behavior?
The Narrative Log can add empty Say commands. [This issue](https://github.com/snozbot/fungus/issues/838) wanted that done away with.

### What is the new behavior?
Thanks to the new RemoveEmptyNarrativeLogEntries component (added to the NarrativeLog prefab), empty entries that get added are immediately removed. 

### Important Notes

- My changes require modifications or additions to documentation
   * Now you can invoke and listen for entry removals for these components: NarrativeLog and NarrativeLogEntryUI
- My changes modify the runtime execution/behaviour of the SBNS
- My changes modify the NarrativeEntryLogTest Fungus Example
- Added comments explaining many of the changes. Look in these scripts for the important stuff:
  * NarrativeLog.cs
  * NarrativeLogEntryUI.cs
  * NarrativeLogMenu.cs
  * RemoveEmptyNarrativeLogEntries.cs
- To see the changes in action, run the NarrativeEntryLogTest scene.

### CODE REVIEW

**Comment by CG-Tespy** [comment]
Unfortunately, Github won't give me the option; it just says that my branch is 2 commits ahead of the official one, and none behind. What should I do?

**Comment by breadnone** [comment]
> 
> 
> Unfortunately, Github won't give me the option; it just says that my branch is 2 commits ahead of the official one, and none behind. What should I do?

If you're doing git pull remote branch, try to 'git fetch' after... or git pull --rebase usually do the trick

**Comment by CG-Tespy** [comment]
I did that, and I just got the message that the branch is up to date. Based on what I know of how Git works, it seems that my commits here don't actually break anything in the official develop branch... Is there something I'm missing?

**Comment by stevehalliwell** [comment]
It'll be slightly different depending no what git gui you are using, but in general ctrl selecting two commits shows you the differences between them, same as GitHub is doing [here](https://github.com/snozbot/fungus/pull/861/files). In most clients on that screen you can then select to stage or discard (depending on selection order) to undo the many bug fixes that are being undone here.

**Comment by CG-Tespy** [comment]
@stevehalliwell Then should I discard everything that changes things in the official develop branch (besides the stuff I meant to change), or...?

**Comment by CG-Tespy** [comment]
Figured I'm better off doing this all over again; I've been having a bit of a hard time with the interface, and Google's not helping :/

**Pull request closed without merging**
