### PR TITLE
Portrait location change to inline or stage

### PR DESCRIPTION
**Pull request by lealeelu**
In the conversation system, we want to add the ability to move the portrait from the stage to inline on the say dialog and back again using the "inline" and "stage" option params.

### CODE REVIEW

**Comment by lealeelu** [comment]
Added the tests. Still working on making them pass.

**Comment by chrisgregan** [comment]
Ok cool, good luck!

**Comment by lealeelu** [comment]
I have the bare-bones portrait switching working. I want to add some more tests to check when there are multiple characters on the stage that switch back and forth.
@chrisgregan , are there any other strange cases you can think of that I should test?

**Comment by chrisgregan** [comment]
Is this ready to merge now or have you more to do on it?

**Comment by lealeelu** [comment]
I'm going to look over it a bit more.

**Comment by lealeelu** [comment]
I'm rethinking how we should do this. What if we treat "inline" as if it were just another stage position like "left", "right" and "middle". So instead of....
john right: on stage right
john inline: now I'm in the dialog box
john stage right: back on stage right

john right: on stage right
john inline: now I'm in the dialog box
john right: back on stage right

Although, would we get weird transitions going from stage to inline as if it were trying to animate on stage?

**Comment by chrisgregan** [comment]
I like this option, it's much cleaner than adding a whole new param type. 

The conversation manager would need to be aware of the special 'inline' stage position and correctly handle switching between the two modes. To be safe, we could log an error message if the stage contains a position with the name 'inline'.

**Comment by lealeelu** [comment]
Sounds good to me! I'll fix that up.

**Comment by lealeelu** [comment]
Going to start a new branch.

**Comment by andyandy2015** [comment]
Thanks a lot for this. Question: Does it work when I have custom dialog box per each character? Thanks.

**Comment by lealeelu** [comment]
It should as long as the custom dialog still has the portrait game object to put it into.

**Comment by andyandy2015** [comment]
Ok. Thanks. I will try

**Pull request closed without merging**
