### PR TITLE
[WIP] Add toggle to run Fungus on unscaled time.

### PR DESCRIPTION
**Pull request by esklarski**
### Description
These changes enable Fungus to run while `Time.timeScale == 0`.

### What is the current behavior?
If `Time.timeScale` is set to `0` Fungus is paused and uninteractable

### What is the new behavior?
I made these changes, sans switch, for a project where I used Fungus for all the menus. I needed to pause 3d gameplay but have a character come up to act as the pause screen menu.

Behaviour Now:
- Fungus remains interactable while `Time.timeScale == 0`

### Important Notes
- My change require modifcations or additions to documentation
- My change modifies the runtime execution/behaviour of existing Fungus Features. e.g., Say, Menus, Portraits, etc.
- My change adds demos to FungusExamples -- coming soon

### Other information
Still a work in progress:
- Need advising on location of behaviour switch (currently FungusManager.cs)
- I need to install the correct version of Unity before I can proceed
- Testing needs to happen
- I'll transfer the demo scene I put together

### CODE REVIEW

**Comment by breadnone** [comment]
Proly wrap it as extension instead of hard coding it?

**Comment by esklarski** [comment]
I'm not sure extension methods can do all that this needs.

I'm more wondering, if there is any reason to pause Fungus? The simplest would be to eliminate all of the if/else logics and just run Fungus on unscaled time always.

**Comment by breadnone** [comment]
That would introduce breaking change, lots of users pausing their games with it

**Comment by esklarski** [comment]
Well that's why the effort. I hard coded it for my purposes, and didn't need to make a toggle.

**Comment by esklarski** [comment]
Demo scene added.

**Comment by esklarski** [comment]
I've done a bit more research and I can clean this up substantively.

Putting a YieldInstruction function like:
`public static YieldInstruction WaitForAdjustedSeconds(float seconds) =>
            useUnscaledTime ? new WaitForSecondsRealtime(seconds) : new WaitForSeconds(seconds);`
allows all of the if/else logic to be removed, with scripts only needing to call this one function instead of having a second wait function each and supporting logic:
`yield return FungusManager.Instance.WaitForAdjustedSeconds(value);`

It'll be a few days before I can cleanup the commit tree here.

**Pull request closed without merging**
