### PR TITLE
Playground Project

### PR DESCRIPTION
**Pull request by stevehalliwell**
As per #632 

Adds commands, a Rigidbody2D variable type, updates the documentation to include it and updates the changelog to include everything all the way back to mainline commit tagged 3.6.0

### CODE REVIEW

**Comment by chrisgregan** [comment]
These demos are cool! Really shows how you can use Fungus in a similar way to Scratch to make simple games easily.

I noticed that the Cannon and Spawner prefabs in Playground/Prefabs have missing scripts.

**Comment by chrisgregan** [comment]
Readme looks good Steve, you planning to merge this now? I'm putting together the release notes for the next release.

**Comment by stevehalliwell** [comment]
Cool, just wanted to give chance for comments. Merged it in.

**Comment by chrisgregan** [comment]
Cheers Steve!

**Pull request merged**
