### PR TITLE
Playmaker Fungus Integration

### PR DESCRIPTION
**Pull request by Nilihum**
Playmaker-Fungus Integration Scripts.unitypakage contains code that
1) Can execute a Fungus Block from Playmaker
2) Call a Global Event in Playmaker (and thus cause a state transition) from Fungus
3) Write Playmaker variable values  to Fungus variables (String, Integer, Float, Bool)
4) Read Fungus variable values and copy them into Playmaker variables (String, Integer, Float, Bool)

### CODE REVIEW

**Comment by chrisgregan** [comment]
Thanks for the PR Nihilum. I got the unitypackage installed and took a look at the scripts - looks good! 

Here's some feedback:
- The .unitypackage should be in the fungus/Assets/Fungus/Integrations folder
- The code should follow the Fungus [coding standard](http://fungusdocs.snozbot.com/coding_standard.html) and remove commented out code.
- Provide an example scene (or scenes) which demonstrate some common usage scenarios
- Provide a readme text file which explains how to use the extension (in the unitypackage)
- Organise the files in the extension by type. i.e. Scripts, Scenes, etc. subfolders.

Once there's an example scene in there I might be able to offer more feedback on the actual functionality. Great work so far anyhow!

**Comment by Nilihum** [comment]
Still trying to get the hang of pull requests, but here's what I've done:

-Organized files in extension by type.
-Provided Readme file
-Created Example scene
-Code follows Fungus coding standards, removed commented out code.
-.unitypackage placed in Integrations file.

Any feedback or advice you could give will be greatly appreciated. Thanks again.

**Comment by chrisgregan** [comment]
Ran the example scene and everything looks to work great!

Here's some feedback to tidy up the code and file layout:
- The package should be called "Fungus-PlayMaker.unitypackage"
- The package and its readme should be inside a folder called "PlayMaker"
- The install instructions should explain what PlayMaker is, how to install both it and the unity
- Change FungusStateTransition.cs to below code to match the coding standard
```
using UnityEngine;
using Fungus;

namespace Fungus
{
    ///<summary>
    ///Trigger a global state transition in the Playmaker FSM
    ///</summary>
    [CommandInfo("Playmaker",
                 "Global State Transition",
                 "Send an event from Fungus to Playmaker")]
    public class FungusStateTransition : Command
    {
        [Tooltip("What this does")]
        [SerializeField] protected PlayMakerFSM FSM;

        [Tooltip("and this!")]
        [SerializeField] protected string destinationEvent;

        #region Public methods

        /// <summary>
        /// Trigger input Global State Transition in input FSM
        /// </summary>
        public override void OnEnter()
        {
            FSM.SendEvent(destinationEvent);
            Continue();
        }

        #endregion
    }
}
```
- Looks like the PlayMaker action classes also need to be updated to the coding standard? I don't know if PlayMaker actions require the fields to be public, but if possible they should be [SerializedField] protected instead for better encapsulation. 
- I'd also make all methods use the same capitalization style, put public methods into a "#region Public methods" block and add summary comments for all public methods.

**Comment by Nilihum** [comment]
Alright, I've made a PR with those changes. Playmaker can't have variables that are [SerializedField] protected, though, they need to be public to work.

**Comment by chrisgregan** [comment]
Looks great - thanks very much for the contribution!

btw happy to provide a reference, quote, etc. if you need it for your project.

**Pull request merged**
